---
- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
  register: kube_home

- debug: var=kube_home

- name: Setup client config
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
  when: kube_home.changed

