---
- name: Test K8s install state
  failed_when: off
  stat:
    path: /etc/kubernetes/kubeadm_init.log
  register: k8s_init_log

- debug: var=k8s_init_log.stat

- name: Initialize K8s cluster
  shell:
    cmd: kubeadm init
  register: kubeadm_init
  when: not k8s_init_log.stat.exists

- debug: var=k8s_init.stdout
  when: not k8s_init_log.stat.exists

- name: Wait for K8s to start
  wait_for:
    port: 6443

- name: Save install log
  shell:
    cmd: echo -e "{{ kubeadm_init.stdout }}" > /etc/kubernetes/kubeadm_init.log
  when: kubeadm_init.changed
