---
- name: Setup k8s Control Plane
  become: true
  hosts: control[0]
  roles:
    - control-node
  tags:
    - init-control

- name: Setup k8s Control Plane
  become: true
  hosts: control[1:]
  roles:
    - control-node
  tags:
    - join-control

- name: Setup k8s Workers
  become: true
  hosts: worker
  roles:
    - worker-node
