- name: Check if there is swap
  changed_when: off
  shell:
    cmd: swapon -s | wc -l
  register: swap

- name: Turn off swap
  shell:
    cmd: swapoff /swap.img
  when: swap.stdout | int > 0

- name: Disable swap in fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^([^#]+swap.*$)'
    line: '#\1' 
    backrefs: yes

