---
- name: Enable network bridge in sysctl
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  register: k8s_sysctl

- name: Reload host sysctls
  shell:
    cmd: sysctl --system
  when: k8s_sysctl.changed
